import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MainMenu from '@/components/MainMenu';
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Analytics } from "@vercel/analytics/react"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Thao Truong's portfolio",
  description: "Generated by create next app",
  icons: {
    icon: '/img/logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
          <meta property="og:title" content="Thao Truong portfolio" />
          <meta property="og:description" content="Welcome to my page" />
          <meta property="og:image" content="/img/thumbnail_link.png" />
          <meta name="twitter:card" content="summary_large_image" />
          <meta name="format-detection" content="telephone=no" />
          <Analytics/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <MainMenu/>
      </body>
    </html>
  );
}
