import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MainMenu from '@/components/MainMenu';
import PopupWarningReponsive from '@/components/PopupWarningReponsive';
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Thao Truong's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
          <meta property="og:title" content="My Awesome Page" />
          <meta property="og:description" content="This is an amazing page with awesome content!" />
          <meta property="og:image" content="/img/thumbnail_link.png" />
          <meta name="twitter:card" content="summary_large_image" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <MainMenu/>
        <PopupWarningReponsive/>
      </body>
    </html>
  );
}
